[package]
name = "util"
version = "0.1.0"
authors = ["Michael Lazear <lazear@scripps.edu>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "unsafe_arena"
harness = false

[[bench]]
name = "safe_arena"
harness = false